default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: repairs_api_development

test:
  <<: *default
  database: repairs_api_test

production:
  <<: *default
  database: repairs_api_production
  username: repairs_api
  password: <%= ENV['REPAIRS_API_DATABASE_PASSWORD'] %>
